<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.axway.ats.framework.agent</groupId>
        <artifactId>ats-agent</artifactId>
        <version>4.5.2-log4j1-SNAPSHOT</version>
    </parent>

    <groupId>com.axway.ats.framework.agent.standalone</groupId>
    <artifactId>ats-agent-standalone</artifactId>
    <packaging>pom</packaging>
    <name>ATS-Agent-Standalone</name>

    <modules>
        <module>containerstarter</module>
        <module>systemoperations</module>
        <module>all</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.eclipse.jetty.ee10</groupId>
                <artifactId>jetty-ee10-servlet</artifactId>
                <version>${eclispe.jetty.version}</version>
                <scope>runtime</scope>
            </dependency>
            <dependency> <!-- transitive dependency -->
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-session</artifactId>
                <version>${eclispe.jetty.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency> <!-- transitive dependency -->
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-ee</artifactId>
                <version>${eclispe.jetty.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency> <!-- transitive dependency -->
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-security</artifactId>
                <version>${eclispe.jetty.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency> <!-- transitive dependency -->
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-xml</artifactId>
                <version>${eclispe.jetty.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency> <!-- transitive dependency -->
                <groupId>org.glassfish.pfi</groupId>
                <artifactId>pfi-basic</artifactId>
                <version>5.1.0</version>
                <scope>provided</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>

</project>
