<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.axway.ats.framework</groupId>
        <artifactId>ats-framework</artifactId>
        <version>4.5.2</version>
    </parent>

    <groupId>com.axway.ats.framework.agent</groupId>
    <artifactId>ats-agent</artifactId>
    <packaging>pom</packaging>
    <name>ATS-AGENT</name>

    <modules>
        <module>core</module>
        <module>agentapp</module>
        <module>webapps</module>
    </modules>

    <properties>
        <jakarta.servlet.servlet-api.version>6.1.0</jakarta.servlet.servlet-api.version>
        <com.sun.jaxws.version>4.0.3</com.sun.jaxws.version>
        <eclispe.jetty.version>12.0.25</eclispe.jetty.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <dependency> <!-- For the ACGen task -->
                <groupId>org.apache.ant</groupId>
                <artifactId>ant</artifactId>
                <version>1.10.11</version>
            </dependency>
            <dependency>
                <groupId>xerces</groupId>
                <artifactId>xercesImpl</artifactId>
                <version>${apache.xercesImpl.version}</version>
            </dependency>
            <dependency> <!-- for Agent webapp, all components - Jersey-server -->
                <groupId>jakarta.servlet</groupId>
                <artifactId>jakarta.servlet-api</artifactId>
                <version>${jakarta.servlet.servlet-api.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.eclipse.jetty.ee10</groupId>
                <artifactId>jetty-ee10-webapp</artifactId>
                <version>${eclispe.jetty.version}</version>
            </dependency>
            <dependency>
                <groupId>org.fusesource</groupId>
                <artifactId>sigar</artifactId>
                <version>1.6.4</version>
            </dependency>
            <dependency>
                <groupId>com.github.oshi</groupId>
                <artifactId>oshi-core</artifactId>
                <version>${oshi.version}</version>
            </dependency>
            <dependency>
                <groupId>com.sun.xml.ws</groupId>
                <artifactId>jaxws-rt</artifactId>
                <version>4.0.3</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.metro</groupId>
                <artifactId>webservices-rt</artifactId>
                <version>4.0.4</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.metro</groupId>
                <artifactId>webservices-api</artifactId>
                <version>4.0.4</version>
            </dependency>
            <dependency>
                <groupId>jakarta.jws</groupId>
                <artifactId>jakarta.jws-api</artifactId>
                <version>3.0.0</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
