<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.axway.ats.framework.agent.standalone</groupId>
        <artifactId>ats-agent-standalone</artifactId>
        <version>4.5.2-log4j1-SNAPSHOT</version>
    </parent>

    <artifactId>ats-agent-standalone-containerstarter</artifactId>
    <name>ATS-Agent-Standalone-ContainerStarter</name>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>com.axway.ats.agentapp.standalone.ContainerStarter</mainClass>
                            <classpathPrefix>container/</classpathPrefix>
                            <!-- <classpathLayoutType>custom</classpathLayoutType> <customClasspathLayout></customClasspathLayout> -->
                        </manifest>
                        <manifestEntries>
                            <Premain-Class>com.axway.ats.agentapp.standalone.ContainerStarter</Premain-Class>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <!--<groupId>log4j</groupId>
            <artifactId>log4j</artifactId>-->
            <groupId>ch.qos.reload4j</groupId>
            <artifactId>reload4j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty.ee10</groupId>
            <artifactId>jetty-ee10-webapp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jetty.ee10</groupId>
            <artifactId>jetty-ee10-servlet</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency> <!-- transitive dependency -->
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-session</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency> <!-- transitive dependency -->
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-ee</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency> <!-- transitive dependency -->
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-security</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency> <!-- transitive dependency -->
            <groupId>org.eclipse.jetty</groupId>
            <artifactId>jetty-xml</artifactId>
            <scope>runtime</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.glassfish.pfl/pfl-basic -->
        <dependency>
            <groupId>org.glassfish.pfl</groupId>
            <artifactId>pfl-basic</artifactId>
            <version>5.1.0</version>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-reload4j</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- <dependency> TODO Check <groupId>javassist</groupId> <artifactId>javassist</artifactId>
            <version>3.12.1.GA</version> </dependency> -->
    </dependencies>
</project>
